{% set name = "coin3d-rt" %}
{% set version_superglue = "1.3.0" %}
{% set sha256_superglue = "f408adcfb706e7c781db9c218ef9e8ba56d43995ccb61dffad5f6154c34f17d6" %}

package:
    name: {{ name }}
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'failed') }}

source:
    - git_url : ../../

    - url: https://github.com/coin3d/superglu/archive/superglu-{{ version_superglue }}.tar.gz
      sha256: {{ sha256_superglue }}
      folder: ../../superglue
      patches:
        - superglue.patch

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libXxf86vm') }}  # [linux]
        - cmake 3.18.*
        - ninja
    host:
        - boost-cpp
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxi  # [linux]
        - expat
    run:
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxi  # [linux]
        - expat

# test:
#     requires:
#         - {{ cdt('mesa-libgl-devel') }}  # [linux]
#         - {{ compiler('c') }}
#         - {{ compiler('cxx') }}
#     files:
#         - test.cpp  # [linux]
#     commands:
#         - ${CXX} -o test test.cpp -Wl,-rpath-link -lCoin -L${PREFIX}/lib/ -I${PREFIX}/include/  # [linux]
#         - ./test  # [linux]
#         - where /r "%PREFIX%"  Coin4.dll  # [win]
#         - test -f ${PREFIX}/lib/libCoin.dylib  # [osx]

about:
    home: https://github.com/realthunder/coin
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Coin3D with improved shadow renderering
    description: Coind3D with improved support of shadow rendering 

extra:
    recipe-maintainers:
        - realthunder
