{% set name = "pivy-rt" %}
{% set version = "0.6.8" %}
{% set sha256 = "c443dd7dd724b0bfa06427478b9d24d31e0c3b5138ac5741a2917a443b28f346" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  url: https://github.com/coin3d/pivy/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - msinttypes      # [win]
    - cmake
    - ninja
    - swig
  host:
    - python
    - coin3d-rt
    - soqt-rt
    - qt
    - moab * mpi_mpich_tempest_*   # [osx]
  run:
    - python
    - coin3d-rt
    - qt
    - pyside2
    - soqt-rt
    - moab * mpi_mpich_tempest_* # [osx]

test:
  imports:
    - sys
    - pivy.coin
    # - pivy.gui.soqt

about:
  home: https://github.com/realthunder/coin
  license: ISC
  license_file: LICENSE
  summary: python bindings to coin3d with enhanced shadow rendering.

extra:
  recipe-maintainers:
    - realthunder
