name: Publish conda

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda build for ${{ matrix.os }} ${{ matrix.arch }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: false
      matrix:
        os: [macos-11, ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        arch : ["64"]
        include:
          - os: windows-latest
            python-version: "3.8"
            arch : "64"
          - os: ubuntu-latest
            arch: aarch64
            python-version: "3.10"
          - os: macos-11
            arch: arm64
            python-version: "3.10"

    steps:
      - uses: actions/checkout@v3
      - name: Conda environment creation and activation
        uses: realthunder/setup-miniconda@main
        with:
          python-version: ${{ matrix.python-version }}
          conda-build-version: "*"
          # mamba-version: "*"
          # use-mamba: true
          # miniforge-version: latest
          environment-file: conda/build_env.yaml    # Path to the build conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      # - name: Install mamba build
      #   shell: bash -el {0}
      #   run: mamba install boa -c conda-forge
      - name: Set build variant
        shell: bash -el {0}
        run: |
          if ${{ startsWith(matrix.os, 'macos') }}; then
            platform=osx
          elif ${{ startsWith(matrix.os, 'windows') }}; then
            platform=win
          else
            platform=linux
          fi
          printf "target_platform:\n  - %s-%s\n" $platform ${{ matrix.arch }} > conda/variant.yaml
          cat conda/variant.yaml
      - name: Build and upload the conda packages
        uses: realthunder/action-build-and-upload-conda-packages@main
        with:
          meta_yaml_dir: conda/00-coin conda/01-soqt conda/02-pivy
          python-version: ${{ matrix.python-version }}
          variant_conf: conda/variant.yaml
          # mambabuild: true
          user: realthunder
          label: main
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the right name of your secret
